### ISSUE TITLE
Great Plugin But Crashes My Browser - Mac OSX

### ISSUE THREAD

**Issue by mashaalmemon** [tomimick/chrome-ext-page-size#1]
Hi There,

I found this plugin for chrome and attempted to use it. It appeared to work wonderfully however after running for about 1 minute as I interacted with a page, it crashed chrome and caused Mac OSX to log me out.

I tested it out on this [page](https://www.walmart.ca/en/ip/george-girls-lace-swing-top-pink/6000196592596). I added the product to the cart and attempted to checkout.

At a high level, I imagine it is likely running out of memory in some way at runtime? Any idea what might be causing this?

**Comment by tomimick** [comment]
Sorry for being slow here, I tested+noted your issue and then forgot it...

Still can't reproduce a crash when doing anon checkout. Can you? Crash caused OSX to log you out from computer!? Wonder how this is even possible...

Just released ver 1.0.3 but it should not have effect here.
