### ISSUE TITLE
Removed from chrome store

### ISSUE THREAD

**Issue by RarogCmex** [tomimick/chrome-ext-page-size#2]
Returns 404:
https://chrome.google.com/webstore/detail/oepnndnpjiahgkljgbohnnccmokgcoln

**Comment by RarogCmex** [comment]
Also it seems that extension does not display new video formats

**Comment by Lucas-C** [comment]
This extension is still present on the Chrome store:
https://chrome.google.com/webstore/detail/page-size-inspector/oepnndnpjiahgkljgbohnnccmokgcoln
