### ISSUE TITLE
Does not work with local files

### ISSUE THREAD

**Issue by francisbarton** [tomimick/chrome-ext-page-size#4]
I wanted to use this to see what is making up the size of a local HTML file - how much of it is images, how much is scripts, how much is just HTML etc etc.
I am not interested in its network performance as it is just loading from local disk.
When I click on the extension icon I get the message
`Cannot attach to this target.`

**Comment by tomimick** [comment]
This is a limitation of the system. chrome.debugger.attach() denies attaching to local files.

Serve the local files via http server (like "python3 -m http.server") and then inspect.

**Comment by francisbarton** [comment]
Thanks Tomi, no problem.
